#                                                                                                      
#,-.----.                                                                                              
#\    /  \                                             ,---,                        ___      ,---,     
#|   :    \   ,--,                                    '  .' \                     ,--.'|_  ,--.' |     
#|   |  .\ :,--.'|                                   /  ;    '.             ,--,  |  | :,' |  |  :     
#.   :  |: ||  |,     ,----._,.  ,----._,.          :  :       \          ,'_ /|  :  : ' : :  :  :     
#|   |   \ :`--'_    /   /  ' / /   /  ' /     .--, :  |   /\   \    .--. |  | :.;__,'  /  :  |  |,--. 
#|   : .   /,' ,'|  |   :     ||   :     |   /_ ./| |  :  ' ;.   : ,'_ /| :  . ||  |   |   |  :  '   | 
#;   | |`-' '  | |  |   | .\  .|   | .\  ., ' , ' : |  |  ;/  \   \|  ' | |  . .:__,'| :   |  |   /' : 
#|   | ;    |  | :  .   ; ';  |.   ; ';  /___/ \: | '  :  | \  \ ,'|  | ' |  | |  '  : |__ '  :  | | | 
#:   ' |    '  : |__'   .   . |'   .   . |.  \  ' | |  |  '  '--'  :  | : ;  ; |  |  | '.'||  |  ' | : 
#:   : :    |  | '.'|`---`-'| | `---`-'| | \  ;   : |  :  :        '  :  `--'   \ ;  :    ;|  :  :_:,' 
#|   | :    ;  :    ;.'__/\_: | .'__/\_: |  \  \  ; |  | ,'        :  ,      .-./ |  ,   / |  | ,'     
#`---'.|    |  ,   / |   :    : |   :    :   :  \  \`--''           `--`----'      ---`-'  `--''       
#  `---`     ---`-'   \   \  /   \   \  /     \  ' ;                                                   
#                      `--`-'     `--`-'       `--`                                                    

events:
  #If enabled, interaction with blocks will be allowed when not authenticated
  allow-block-interact: false
  #If enabled, dropping items will be allowed when not authenticated
  allow-item-drop: false
  #If enabled, picking up items will be allowed when not authenticated
  allow-item-pickup: false
  #If enabled, picking up arrows will be allowed when not authenticated
  allow-arrow-pickup: false
  #If enabled, hitting others will be allowed when not authenticated
  allow-damage-others: false
  #If enabled, placing blocks will be allowed when not authenticated
  allow-block-place: false
  #If enabled, breaking blocks will be allowed when not authenticated
  allow-block-break: false
  #If enabled, xp changes will be allowed when not authenticated
  allow-xp-change: false
  #If enabled, effect time will still go when not authenticated
  allow-effect-tick: false
  #If enabled, movement will be will be allowed when not authenticated
  allow-movement: false
  #if enabled, head movement will be allowed when not authenticated
  allow-head-movement: true
  #If enabled, eating will be allowed when not authenticated
  allow-eating: false
  #If enabled, commands (other than /login, /register, /forgetpassword, /sendpin) will be allowed when not authenticated
  allow-commands: false
  #If enabled, hunger will not be stopped when not authenticated
  allow-hunger: false
  #If enabled, damage will not be stopped when not authenticated
  allow-damage: false
  #If enabled, healing will not be stopped when not authenticated
  allow-heal: false
login:
  #If enabled, you can login without /login
  chat-login: true
  #If enabled, you will be authenticated automatically if your uuid matches the last uuid used.
  auto-authentication: false
  #If enabled, players with logged in with xbox are automatically registered/logged in. (ClearSky only!)
  xbox-bypass: false
  #Disable authentication for these usernames
  accounts-bypassed: ["steve"]
  #Tries before kicked
  tries: 5
  #Return to spawn when logged in
  return-to-spawn: false
  #If on, players will be set to adventure mode til logged in
  adventure-mode: true
  #If enabled, players joining when another player has their username is kicked
  single-session: true
  #Limit of players allowed to login with same IP
  ip-limit: 3
register:
  #Minimum password length
  minimum-password-length: 6
  #Passwords you want blocked
  blocked-passwords: ["password", "123456", "abc123", "abcdef", "qwerty"]
  #Accounts you want blocked
  blocked-accounts: ["notch"]
  #Capes will be given for registered players
  cape-for-registration: true
pin: 
  cant-use-pin: ["Owner"]
timeout:
  #Kick players after certain time
  enabled: true
  #Seconds before kicked if not authenticated
  timeout-time: 60
effects:
  #If enabled, players will be invisible til authentication
  invisible: true
  #If enabled, players will be blind til authentication
  blindness: true
  #Hide items til logged in
  hide-items: true
  #Hides all players til logged in
  hide-players: true
  #Hides true health til logged in
  hide-health: true
  #Hides true hunger til logged in
  hide-hunger: true
  #Hides true xp til logged in
  hide-xp: true
  #Hides effects til logged in
  hide-effects: true
message:
  #Default Language
  #Available Languages: eng, cze, ger, por, chs
  lang: eng
  #If enabled, a popup will be shown when not authenticated
  popup: true
  #If enabled, a tip will be shown when not authenticated
  tip: true
  #If enabled, a title will be shown when not authenticated
  title: true
  #If enabled, a subtitle will be shown when not authenticated
  subtitle: true
  #If enabled, a actionbar will be shown when not authenticated
  actionbar: true
  #If enabled, a boss bar will be shown when not authenticated
  boss-bar: true
  #Seconds til next message
  seconds-til-next-message: 5
  #If enabled, players can see chat messages when not authenticted
  see-messages: false
  #If on, will prevent join message til logged in
  hold-join-message: true
  #If on, there will be a seperate join message for new players
  join-message-for-new-players: true
progress-reports:
  #Send progress reports every certain number of players registered 
  enabled: true
  #Email to send progress report to
  progress-report-email: youremail@gmail.com
  #Number of players before send progress report
  progress-report-number: 100
  #What progress report says
  progress-report: "Your server ({ip}:{port}) has reached {players} players! Your {players}th player is {player}."
emails:
  send-email-on-resetpassword: true
  send-email-on-changepassword: true
  send-email-on-attemptedlogin: true
  send-email-on-login-from-new-ip: true
  mailgun:
    api: YOUR_KEY
    public-api: YOUR_PUBLIC_KEY
    domain: YOUR_DOMAIN
    from: PiggyAuth <postmaster@YOUR_DOMAIN>
vipslots:
  #Players with VIP slot
  players: [MCPEPIG] 
  #Ranks with VIP slot
  ranks: ["Owner"]
key:
  #If enabled, there will be a special key that resets every 5 mins and after every use to allow access to any account.
  enabled: true
  #Username of owner, for key
  owner: TheOwnerLovesPig
#Database (sqlite3, mysql, yaml, json)
database: sqlite3
#MySQL login
mysql:
  host: host
  user: user
  name: name
  password: password
  port: 3306
hash:
  cost: 15
auto-updater:
  enabled: true
  auto-install: true
